const KEY='shashwat_inventory_v3';
const defaults=[
{id:'d1',brand:'Honda',model:'City',variant:'VX',year:2020,price:865000,fuel:'Petrol',transmission:'Manual',km:58000,type:'Sedan',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#323a48'},
{id:'d2',brand:'Hyundai',model:'Verna',variant:'SX',year:2022,price:1245000,fuel:'Petrol',transmission:'Automatic',km:32000,type:'Sedan',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#222b37'},
{id:'d3',brand:'Maruti Suzuki',model:'Ciaz',variant:'Zeta',year:2021,price:795000,fuel:'Petrol',transmission:'Manual',km:47000,type:'Sedan',location:'Bhopal',featured:false,status:'AVAILABLE',color:'#e9e9e5'},
{id:'d4',brand:'Maruti Suzuki',model:'Baleno',variant:'Alpha',year:2021,price:725000,fuel:'Petrol',transmission:'Manual',km:36000,type:'Hatchback',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#1d4e83'},
{id:'d5',brand:'Hyundai',model:'i20',variant:'Asta',year:2022,price:875000,fuel:'Petrol',transmission:'Automatic',km:29000,type:'Hatchback',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#d5222a'},
{id:'d6',brand:'Tata',model:'Altroz',variant:'XZ+',year:2021,price:750000,fuel:'Petrol',transmission:'Manual',km:41000,type:'Hatchback',location:'Bhopal',featured:false,status:'AVAILABLE',color:'#c7a630'},
{id:'d7',brand:'Hyundai',model:'Creta',variant:'SX',year:2022,price:1285000,fuel:'Petrol',transmission:'Automatic',km:42000,type:'SUV',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#143c6c'},
{id:'d8',brand:'Kia',model:'Seltos',variant:'HTK+',year:2021,price:1125000,fuel:'Diesel',transmission:'Manual',km:47000,type:'SUV',location:'Bhopal',featured:true,status:'AVAILABLE',color:'#121619'},
{id:'d9',brand:'Tata',model:'Nexon',variant:'XZ+',year:2022,price:895000,fuel:'Diesel',transmission:'Manual',km:51000,type:'SUV',location:'Bhopal',featured:false,status:'AVAILABLE',color:'#687250'},
{id:'d10',brand:'Mahindra',model:'XUV300',variant:'W8',year:2020,price:795000,fuel:'Diesel',transmission:'Manual',km:63000,type:'SUV',location:'Bhopal',featured:false,status:'AVAILABLE',color:'#a52629'}];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(x)&&x.length)return x}catch{}localStorage.setItem(KEY,JSON.stringify(defaults));return structuredClone(defaults)}
function save(x){localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('inventorychange'))}
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function carSvg(c){const col=c.color||'#2f3b49';const suv=c.type==='SUV', hatch=c.type==='Hatchback';const roof=suv?'M150 128 C195 55 290 44 382 52 C438 56 480 79 520 122':hatch?'M155 130 C208 72 280 56 365 62 C416 66 452 86 480 125':'M145 130 C215 66 294 54 392 62 C444 66 486 89 520 124';return `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 640 300'><defs><linearGradient id='g' x1='0' x2='1'><stop stop-color='${col}'/><stop offset='.55' stop-color='${col}'/><stop offset='1' stop-color='#111820'/></linearGradient></defs><ellipse cx='330' cy='236' rx='220' ry='18' fill='rgba(0,0,0,.18)'/><path d='${roof} L565 143 C594 148 610 170 610 196 L606 215 L548 218 C540 180 510 157 472 157 C434 157 403 182 397 220 L224 220 C218 182 188 157 150 157 C112 157 82 182 76 219 L43 214 C38 181 55 157 88 147 L145 132 Z' fill='url(#g)'/><path d='M185 126 L225 83 L370 78 C410 79 444 93 474 124 Z' fill='#abc0ce' opacity='.5'/><circle cx='151' cy='218' r='49' fill='#111820'/><circle cx='151' cy='218' r='24' fill='#777f85'/><circle cx='472' cy='218' r='49' fill='#111820'/><circle cx='472' cy='218' r='24' fill='#777f85'/></svg>`}
function imageSrc(c){return c.image||'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(carSvg(c))}
function card(c){return `<article class="car"><div class="car-img"><img src="${imageSrc(c)}" alt="${c.brand} ${c.model}"><span class="badge">${c.type}</span>${c.featured?'<span class="badge featured">FEATURED</span>':''}</div><div class="car-body"><div class="meta">${c.year} · ${c.fuel} · ${c.transmission}</div><h3>${c.brand} ${c.model}</h3><div class="variant">${c.variant} · ${c.location||'Bhopal'} · ${Number(c.km||0).toLocaleString('en-IN')} KM</div><div class="price">${money(c.price)}</div><div class="card-actions"><button class="btn dark">View Details</button><button class="btn outline">Enquire</button></div></div></article>`}
function renderFeatured(){const el=document.getElementById('featuredCars');if(!el)return;const list=load().filter(c=>c.featured&&c.status!=='HIDDEN'&&c.status!=='SOLD').slice(0,6);el.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No featured cars selected. Open Admin and mark cars as Featured.</div>';const n=document.getElementById('inventoryCount');if(n)n.textContent=load().filter(c=>c.status!=='HIDDEN').length}
let activeType='';function renderInventory(type=activeType){activeType=type;const el=document.getElementById('inventoryGrid');if(!el)return;const list=load().filter(c=>c.status!=='HIDDEN'&&(!type||c.type===type));el.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No cars in this category.</div>';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',(b.dataset.type||'')===type));const count=document.getElementById('found');if(count)count.textContent=list.length+' cars found'}
function resetDemo(){localStorage.setItem(KEY,JSON.stringify(defaults));renderFeatured();renderInventory('');renderAdmin()}
function renderAdmin(){const body=document.getElementById('adminRows');if(!body)return;body.innerHTML=load().map(c=>`<tr><td>${c.brand} ${c.model} ${c.variant}</td><td>${c.type}</td><td>${money(c.price)}</td><td>${c.status}</td><td class="actions"><button class="mini ${c.featured?'on':''}" onclick="toggleFeatured('${c.id}')">${c.featured?'★ Featured':'☆ Home'}</button><button class="mini" onclick="setStatus('${c.id}','AVAILABLE')">Available</button><button class="mini" onclick="setStatus('${c.id}','SOLD')">Sold</button><button class="mini" onclick="setStatus('${c.id}','HIDDEN')">Hide</button><button class="mini" onclick="removeCar('${c.id}')">Delete</button></td></tr>`).join('')}
function toggleFeatured(id){const x=load();const c=x.find(v=>v.id===id);if(c)c.featured=!c.featured;save(x);renderAdmin()}
function setStatus(id,s){const x=load();const c=x.find(v=>v.id===id);if(c)c.status=s;save(x);renderAdmin()}
function removeCar(id){save(load().filter(c=>c.id!==id));renderAdmin()}
function setupAdmin(){const f=document.getElementById('carForm');if(!f)return;renderAdmin();f.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(f),file=fd.get('imageFile');let image=String(fd.get('imageUrl')||'').trim();if(file&&file.size){image=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}const car={id:'u'+Date.now(),brand:fd.get('brand'),model:fd.get('model'),variant:fd.get('variant'),year:+fd.get('year'),price:+fd.get('price'),fuel:fd.get('fuel'),transmission:fd.get('transmission'),km:+fd.get('km'),type:fd.get('type'),location:fd.get('location')||'Bhopal',featured:fd.get('featured')==='on',status:'AVAILABLE',image,color:'#263746'};const x=load();x.unshift(car);save(x);f.reset();renderAdmin();document.getElementById('msg').textContent='Vehicle added. It now appears in inventory'+(car.featured?' and on Home.':'.')})}
window.addEventListener('inventorychange',()=>{renderFeatured();renderInventory();renderAdmin()});document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderInventory();setupAdmin();document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>renderInventory(b.dataset.type||'')))})