const KEY='shashwat_inventory_v11';
const defaults=[
{id:'d1',brand:'Honda',model:'City',variant:'VX',year:2020,price:865000,fuel:'Petrol',transmission:'Manual',km:58000,type:'Sedan',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/honda-city.webp'},
{id:'d2',brand:'Hyundai',model:'Verna',variant:'SX',year:2022,price:1245000,fuel:'Petrol',transmission:'Automatic',km:32000,type:'Sedan',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/hyundai-verna.webp'},
{id:'d3',brand:'Maruti Suzuki',model:'Ciaz',variant:'Zeta',year:2021,price:795000,fuel:'Petrol',transmission:'Manual',km:47000,type:'Sedan',location:'Bhopal',featured:false,status:'AVAILABLE',image:'/cars/maruti-ciaz.webp'},
{id:'d4',brand:'Maruti Suzuki',model:'Baleno',variant:'Alpha',year:2021,price:725000,fuel:'Petrol',transmission:'Manual',km:36000,type:'Hatchback',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/maruti-baleno.webp'},
{id:'d5',brand:'Hyundai',model:'i20',variant:'Asta',year:2022,price:875000,fuel:'Petrol',transmission:'Automatic',km:29000,type:'Hatchback',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/hyundai-i20.webp'},
{id:'d6',brand:'Tata',model:'Altroz',variant:'XZ+',year:2021,price:750000,fuel:'Petrol',transmission:'Manual',km:41000,type:'Hatchback',location:'Bhopal',featured:false,status:'AVAILABLE',image:'/cars/tata-altroz.webp'},
{id:'d7',brand:'Hyundai',model:'Creta',variant:'SX',year:2022,price:1285000,fuel:'Petrol',transmission:'Automatic',km:42000,type:'SUV',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/hyundai-creta.webp'},
{id:'d8',brand:'Kia',model:'Seltos',variant:'HTK+',year:2021,price:1125000,fuel:'Diesel',transmission:'Manual',km:47000,type:'SUV',location:'Bhopal',featured:true,status:'AVAILABLE',image:'/cars/kia-seltos.webp'},
{id:'d9',brand:'Tata',model:'Nexon',variant:'XZ+',year:2022,price:895000,fuel:'Diesel',transmission:'Manual',km:51000,type:'SUV',location:'Bhopal',featured:false,status:'AVAILABLE',image:'/cars/tata-nexon.webp'},
{id:'d10',brand:'Mahindra',model:'XUV300',variant:'W8',year:2020,price:795000,fuel:'Diesel',transmission:'Manual',km:63000,type:'SUV',location:'Bhopal',featured:false,status:'AVAILABLE',image:'/cars/mahindra-xuv300.webp'}];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(x)&&x.length)return x}catch{}localStorage.setItem(KEY,JSON.stringify(defaults));return structuredClone(defaults)}
function save(x){localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('inventorychange'))}
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
function imageSrc(c){return c.image||'/vehicle-placeholder.svg'}
function card(c){return `<article class="car"><div class="car-img"><img src="${imageSrc(c)}" alt="${c.brand} ${c.model}"><span class="badge">${c.type}</span>${c.featured?'<span class="badge featured">FEATURED</span>':''}</div><div class="car-body"><div class="meta">${c.year} · ${c.fuel} · ${c.transmission}</div><h3>${c.brand} ${c.model}</h3><div class="variant">${c.variant} · ${c.location||'Bhopal'} · ${Number(c.km||0).toLocaleString('en-IN')} KM</div><div class="price">${money(c.price)}</div><div class="card-actions"><button class="btn dark">View Details</button><button class="btn outline">Enquire</button></div></div></article>`}
function renderFeatured(){const el=document.getElementById('featuredCars');if(!el)return;const list=load().filter(c=>c.featured&&c.status!=='HIDDEN'&&c.status!=='SOLD').slice(0,6);el.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No featured cars selected. Open Admin and mark cars as Featured.</div>';const n=document.getElementById('inventoryCount');if(n)n.textContent=load().filter(c=>c.status!=='HIDDEN').length}
let activeType='';function renderInventory(type=activeType){activeType=type;const el=document.getElementById('inventoryGrid');if(!el)return;const list=load().filter(c=>c.status!=='HIDDEN'&&(!type||c.type===type));el.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No cars in this category.</div>';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',(b.dataset.type||'')===type));const count=document.getElementById('found');if(count)count.textContent=list.length+' cars found'}
function resetDemo(){localStorage.setItem(KEY,JSON.stringify(defaults));renderFeatured();renderInventory('');renderAdmin()}
function renderAdmin(){const body=document.getElementById('adminRows');if(!body)return;body.innerHTML=load().map(c=>`<tr><td>${c.brand} ${c.model} ${c.variant}</td><td>${c.type}</td><td>${money(c.price)}</td><td>${c.status}</td><td class="actions"><button class="mini ${c.featured?'on':''}" onclick="toggleFeatured('${c.id}')">${c.featured?'★ Featured':'☆ Home'}</button><button class="mini" onclick="setStatus('${c.id}','AVAILABLE')">Available</button><button class="mini" onclick="setStatus('${c.id}','RESERVED')">Reserved</button><button class="mini" onclick="setStatus('${c.id}','SOLD')">Sold</button><button class="mini" onclick="setStatus('${c.id}','HIDDEN')">Hide</button><button class="mini" onclick="removeCar('${c.id}')">Delete</button></td></tr>`).join('')}
function toggleFeatured(id){const x=load();const c=x.find(v=>v.id===id);if(c)c.featured=!c.featured;save(x);renderAdmin()}
function setStatus(id,s){const x=load();const c=x.find(v=>v.id===id);if(c)c.status=s;save(x);renderAdmin()}
function removeCar(id){save(load().filter(c=>c.id!==id));renderAdmin()}
function setupAdmin(){const f=document.getElementById('carForm');if(!f)return;renderAdmin();f.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(f),file=fd.get('imageFile');let image=String(fd.get('imageUrl')||'').trim();if(file&&file.size){image=await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}const car={id:'u'+Date.now(),brand:fd.get('brand'),model:fd.get('model'),variant:fd.get('variant'),year:+fd.get('year'),price:+fd.get('price'),fuel:fd.get('fuel'),transmission:fd.get('transmission'),km:+fd.get('km'),type:fd.get('type'),location:fd.get('location')||'Bhopal',featured:fd.get('featured')==='on',status:'AVAILABLE',image};const x=load();x.unshift(car);save(x);f.reset();renderAdmin();document.getElementById('msg').textContent='Vehicle added. It now appears in inventory'+(car.featured?' and on Home.':'.')})}
window.addEventListener('inventorychange',()=>{renderFeatured();renderInventory();renderAdmin()});document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderInventory();setupAdmin();document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>renderInventory(b.dataset.type||'')))})