import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getVehicleBySlug } from "@/lib/db";
import { LeadForm } from "@/components/LeadForm";
import { VehicleGallery } from "@/components/VehicleGallery";
import { business, phoneHref, whatsappHref } from "@/lib/config";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const v=await getVehicleBySlug(slug);if(!v)return {title:"Car Not Found"};const title=`Used ${v.brand} ${v.model} ${v.variant} ${v.year} in ${v.location}`;return {title,description:`${v.year} ${v.brand} ${v.model} ${v.variant}, ${v.kmDriven.toLocaleString('en-IN')} KM, ${v.fuel}, ${v.transmission}. Enquire with Shashwat Cars.`,alternates:{canonical:`/cars/${v.slug}`},openGraph:{title,description:`${v.year} ${v.brand} ${v.model} ${v.variant} available through ${business.name}.`,images:v.images.slice(0,1)}}}
export default async function VehiclePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const v=await getVehicleBySlug(slug);if(!v||v.status==="HIDDEN")notFound();const structured={"@context":"https://schema.org","@type":"Vehicle",name:`${v.year} ${v.brand} ${v.model} ${v.variant}`,brand:{"@type":"Brand",name:v.brand},model:v.model,vehicleModelDate:String(v.year),mileageFromOdometer:{"@type":"QuantitativeValue",value:v.kmDriven,unitCode:"KMT"},fuelType:v.fuel,vehicleTransmission:v.transmission,offers:{"@type":"Offer",price:v.price,priceCurrency:"INR",availability:v.status==="SOLD"?"https://schema.org/SoldOut":"https://schema.org/InStock",url:`${business.siteUrl}/cars/${v.slug}`}};return <section className="section container"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><div className="detail-grid"><div className="gallery-wrap"><VehicleGallery images={v.images} alt={`${v.brand} ${v.model}`}/><span className={`status detail-status status-${v.status.toLowerCase()}`}>{v.status}</span>{v.id.startsWith('demo-')&&<span className="demo-tag detail-demo">DEMO INVENTORY</span>}</div><aside className="detail-summary"><p className="eyebrow">{v.year} • {v.location}</p><h1>{v.brand} {v.model} <span>{v.variant}</span></h1><p className="detail-price">{money(v.price)}</p><div className="spec-grid">{[["YEAR",v.year],["FUEL",v.fuel],["KM",`${v.kmDriven.toLocaleString('en-IN')} KM`],["TRANSMISSION",v.transmission],["OWNERS",v.ownership],["REGISTRATION",v.registration||"—"]].map(([a,b])=><div key={String(a)}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="stack-actions"><a className="btn btn-accent" href="#price-enquiry">Request Best Price</a><a className="btn btn-dark" href="#inspection-enquiry">Book Inspection</a><a className="btn btn-outline" href={whatsappHref(`Hello, I am interested in ${v.brand} ${v.model} ${v.variant}. Please share details.`)}>WhatsApp</a><a className="btn btn-outline" href={phoneHref()}>Call Now</a></div></aside></div>
<div className="content-grid"><article><h2>Vehicle Overview</h2><p>{v.description}</p><h2>Features</h2>{v.features.length?<div className="feature-grid">{v.features.map(x=><span key={x}>✓ {x}</span>)}</div>:<p>Feature data has not been entered for this vehicle.</p>}</article><aside><div id="price-enquiry" className="card enquiry-card"><h2>Interested in this car?</h2><p>Request the best available price.</p><LeadForm type="PRICE_REQUEST" vehicleId={v.id} vehicleName={`${v.brand} ${v.model} ${v.variant}`} button="REQUEST BEST PRICE"/></div><div id="inspection-enquiry" className="card enquiry-card second-enquiry"><h2>Book an inspection</h2><p>Send your contact details and the team can coordinate a suitable visit.</p><LeadForm type="INSPECTION" vehicleId={v.id} vehicleName={`${v.brand} ${v.model} ${v.variant}`} button="BOOK INSPECTION"/></div></aside></div></section>}
