import Link from "next/link";
import { getVehicles } from "@/lib/db";
import { VehicleCard } from "@/components/VehicleCard";
import { business, phoneHref, whatsappHref } from "@/lib/config";

export default async function Home(){const cars=(await getVehicles()).filter(v=>v.status!=="HIDDEN");const featured=cars.filter(v=>v.featured&&v.status!=="SOLD").slice(0,6);return <>
<section className="hero"><div className="hero-overlay"></div><div className="container hero-content"><p className="eyebrow light">TRUSTED PRE-OWNED CARS IN BHOPAL</p><h1>Find Your Perfect <span>Pre-Owned Car</span></h1><p>Quality Used Cars. Transparent Deals. Trusted Service.</p><div className="hero-actions"><Link className="btn btn-accent" href="/cars">Browse Cars</Link><Link className="btn btn-ghost" href="/sell-your-car">Sell Your Car</Link></div>
<form className="hero-search" action="/cars" method="get"><h2>Find Your Car</h2><div className="search-grid"><input name="brand" placeholder="Brand"/><input name="model" placeholder="Model"/><input name="minPrice" type="number" placeholder="Min Price"/><input name="maxPrice" type="number" placeholder="Max Price"/><select name="fuel"><option value="">Fuel</option><option>Petrol</option><option>Diesel</option><option>CNG</option><option>Electric</option></select><select name="transmission"><option value="">Transmission</option><option>Manual</option><option>Automatic</option></select><input name="year" type="number" placeholder="Year"/><button className="btn btn-accent">SEARCH CARS</button></div></form></div></section>
<section className="section container"><div className="section-head"><div><p className="eyebrow">CURATED INVENTORY</p><h2>Featured Cars</h2></div><Link href="/cars">View all inventory →</Link></div>{featured.length?<div className="vehicle-grid">{featured.map(v=><VehicleCard key={v.id} vehicle={v}/>)}</div>:<div className="empty-state"><h3>Fresh inventory is being prepared.</h3><p>Production vehicles will appear here as soon as they are added by the dealership admin.</p><Link className="btn btn-dark" href="/contact">Contact Shashwat Cars</Link></div>}</section>
<section className="section section-dark"><div className="container trust-grid"><div><p className="eyebrow light">SELL YOUR CAR</p><h2>Turn your current car into your next opportunity.</h2><p>Share your vehicle details and request a competitive valuation from {business.name}. No approval or purchase promise is made until inspection and verification.</p><Link href="/sell-your-car" className="btn btn-accent">Get My Car Valuation</Link></div><div className="trust-card"><span>01</span><h3>Submit Details</h3><p>Tell us about your car and expected price.</p><span>02</span><h3>Inspection</h3><p>Schedule a physical verification with the team.</p><span>03</span><h3>Offer & Follow-up</h3><p>Review the dealership’s valuation and next steps.</p></div></div></section>
<section className="section container"><div className="section-head"><div><p className="eyebrow">VISIT SHASHWAT CARS</p><h2>Ready to see a car in person?</h2></div></div><div className="visit-card"><div><h3>{business.address}</h3><p>Use the verified Google Maps reference for directions. Call/WhatsApp details can be configured by the dealership admin.</p></div><div className="card-actions"><a className="btn btn-dark" href={business.mapsUrl} target="_blank">Get Directions</a><a className="btn btn-outline" href={whatsappHref("Hello, I would like to visit Shashwat Cars.")}>WhatsApp</a><a className="btn btn-outline" href={phoneHref()}>Call</a></div></div></section>
</>}
